CREATE USER TEST_DB IDENTIFIED BY passtest DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE temp QUOTA 250M on USERS;

GRANT CONNECT, RESOURCE, DBA TO TEST_DB;

GRANT CREATE SESSION TO TEST_DB;

GRANT CREATE TABLE TO TEST_DB;

GRANT CREATE VIEW TO TEST_DB;

GRANT CREATE ANY TRIGGER TO TEST_DB;

GRANT CREATE ANY PROCEDURE TO TEST_DB;

GRANT CREATE SEQUENCE TO TEST_DB;

GRANT CREATE SYNONYM TO TEST_DB;
